[package]
name = "myent"
version = "0.1.0"
edition = "2021"

[lib]
name = "myent"
path = "src/lib.rs"

[dependencies]
sea-orm = { version = "0.12", features = [ "sqlx-mysql", "runtime-tokio-rustls", "macros"] }